---
title: "asthma_eda"
author: "Rachel Tao"
date: "2/16/2021"
output: html_document
---

```{r setup, include=FALSE}
# load libraries

library(tidyverse)
library(janitor)
library(readxl)
library(leaflet)

# setup

knitr::opts_chunk$set(
	echo = FALSE,
	fig.asp = 0.6,
	fig.width = 6,
	warning = FALSE,
	out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis")

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

```{r pressure, echo=FALSE}
# load in data

asthma_info <- read_excel("./data/asthma-ed-visit-rates-metadata.xlsx")

asthma <- read_csv("./data/asthma-ed-visit-rates.csv") %>% 
  rename(County_name = Geography)

cali_pop <- read_csv("./data/cali_pop_density.csv") %>% 
  mutate(County_name = str_replace(County_name, " County", ""))

asthma_pop <- left_join(asthma, cali_pop)

asthma_pop %>% select(County_name, Numerator, total_pop, County) %>% 
  filter(is.na(total_pop))

# the asthma dataset has values for all of California in addition to each county

```

```{r}
# clean dataset

asthma_pop <- asthma_pop %>% 
  clean_names() %>% 
  filter(
    strata == "Total Population",
    county_name != "California") %>% 
  select(
    county_name,
    county,
    year,
    age_group,
    numerator,
    rate,
    total_pop,
    pop_density,
    housing_density)

asthma_pop %>% pull(age_group) %>% unique()

asthma_child <- asthma_pop %>% 
  filter(age_group == "Under 18")

asthma_adult <- asthma_pop %>% 
  filter(age_group == "18 and Over")

asthma_pop <- asthma_pop %>% 
  filter(age_group == "All Ages")

# save out only asthma under 18 data for final results
write_csv(asthma_child,
          "data/asthma_under18_cleaned.csv")

```


```{r}
# all ages asthma per county (age-adjusted)

ggplot(asthma_pop, aes(x = year, y = rate, group = year)) +
  geom_boxplot()

asthma_counties_adj <- asthma_pop %>% 
  mutate(
    county_name = factor(county_name),
    county_name = fct_reorder(county_name, rate)
  ) %>% 
  ggplot(aes(x = county_name, y = rate, group = county_name)) +
  geom_boxplot() +
  xlab("") +
  ylab("age-adjusted asthma rate") +
  theme(axis.text.x = element_text(angle = 90))

```


```{r}
# all ages asthma per county (crude)

asthma_pop %>% 
  mutate(
    crude_rate = numerator/total_pop
  ) %>% 
  ggplot(aes(x = year, y = crude_rate, group = year)) +
  geom_boxplot()

asthma_counties_crude <- asthma_pop %>% 
  mutate(
    crude_rate = numerator/total_pop,
    county_name = factor(county_name),
    county_name = fct_reorder(county_name, rate)
  ) %>% 
  ggplot(aes(x = county_name, y = crude_rate, group = county_name)) +
  geom_boxplot() +
  xlab("") +
  ylab("crude asthma rate") +
  theme(axis.text.x = element_text(angle = 90))

```

Get under-18 population by county for offset

```{r}
v10 = load_variables(2010, "sf1", cache = TRUE)

View(v10) # male/female population by age is p0120 something something

```

