---
title: "AAMEHS_finalproj"
author: "Maggie Li (ml4424)"
date: "2/4/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# load libraries
library(tidyverse)
library(leaflet)
library(sf)
library(janitor)
```

## Read in data

OLD Data source: https://data-nifc.opendata.arcgis.com/datasets/historic-perimeters-combined-2000-2018/data?geometry=-96.951%2C-9.831%2C-147.224%2C74.202&orderBy=perimeterdatetime&selectedAttribute=fireyear&where=state%20%3D%20%27CA%27

UPDATED data source: https://hub-calfire-forestry.hub.arcgis.com/datasets/california-fire-perimeters-all 

UPDATED Metadata:
alarm_date = first date of wildfire
cont_date = last date of wildfire (i.e. when it was contained)


```{r read in wildfire perimeter shapefile and filter 2011-2018}
wf_11_18_shp = st_read("data/cali_wildfires/California_Fire_Perimeters-shp/California_Fire_Perimeters__all_.shp") %>% 
  janitor::clean_names() %>%
  filter(year >= 2011)
wf_11_18_shp

# reproject
wildfire_WGS84 <- st_transform(wf_11_18_shp, 4326)

# Note: can probably just use CSV data (see below) for quantitative data manipulation and analysis (e.g. running summary stats and statistical models). shapefile is better for viz if we are including any maps.

```

```{r read in wildfire perimeter csv spreedsheet}
wf_11_18 = read_csv("data/cali_wildfires/California_Fire_Perimeters.csv") %>% 
  janitor::clean_names() %>%
  filter(year >= 2011)
wf_11_18 %>%
  filter(fire_name == "CAMP")
```

## Summary Statistics

Bar graph: x-axis = year (fireyear); y-axis = total acres burned (gisacres)
```{r bar graph for area burned by wildfire 2011-2018}
wf_annual_burned = wf_11_18 %>% 
  group_by(fireyear) %>% 
  summarize(sum(gisacres)) %>% 
  rename(annual_burned = "sum(gisacres)") 

ggplot(data = wf_annual_burned,
       aes(x = fireyear, y = annual_burned)) +
  geom_bar(stat = "identity") + theme_linedraw()
  
```

```{r histogram of all wildfire sizes}
wf_hist = ggplot(wf_11_18,
       aes(x = gisacres)) +
  geom_histogram(bins = 30) +
  geom_density()
wf_hist

# boxplot showing distribution of Class G fires (largest)
wf_11_18 %>% filter(gisacres >= 5000) %>% 
  ggplot(aes(x = fireyear,
           y = gisacres,
           group = fireyear)) +
  geom_boxplot() + theme_linedraw()

# boxplot showing distribution of Class A-F fires (all other fires)
wf_11_18 %>% filter(gisacres < 5000) %>% 
  ggplot(aes(x = fireyear,
           y = gisacres,
           group = fireyear)) +
  geom_boxplot() + theme_linedraw()

# Note: want to include all data in the main analysis, since we hypothesize that smaller fires could still have a health impact on a local level (county level)
```

