---
title: "confounders"
author: "Maggie Li (ml4424)"
date: "2/15/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(janitor)
library(tidycensus)

census_api_key("545c7215e59e244a022aa2f8ba7c4fd66ab3649a")
```

CENSUS DATA

Population Density Data; downloaded from US Census 
```{r population density}
census_pop_density <- read.csv("Data/census_2010_pop_density.csv")
head(census_pop_density)

#keep columns GCT_STUB.target.geo.id2, HD01, SUBHD0401, SUBHD0402 (population and housing density)
census_pop_density <- census_pop_density %>% subset(select = c(GCT_STUB.target.geo.id2,
                                                               HD01,
                                                               SUBHD0401, 
                                                               SUBHD0402,
                                                               GCT_STUB.display.label.1))
#delete first three rows
census_pop_density <- census_pop_density[-c(1,2,3),]
census_pop_density <- census_pop_density %>% 
  dplyr::rename(County = GCT_STUB.target.geo.id2) %>%
  dplyr::rename(total_pop = HD01) %>%
  dplyr::rename(pop_density = SUBHD0401) %>%
  dplyr::rename(housing_density = SUBHD0402) %>% 
  dplyr::rename(county_name = GCT_STUB.display.label.1)

census_pop_density$County <- as.numeric(as.character(census_pop_density$County))
census_pop_density <- census_pop_density %>%
  filter(County <= 56045) %>% 
  filter(County > 1000)  #filter out territories
census_pop_density 
# clean county column by adding leading zero
county_cleaned <- formatC(census_pop_density$County, width = 5, format = "d", flag = "0")

census_pop_density <- cbind(census_pop_density, county_cleaned) %>%
  dplyr::select(-County)

census_pop_density$county_cleaned<- as.factor(census_pop_density$county_cleaned) 
census_pop_density <- census_pop_density %>% dplyr::rename(County = county_cleaned)

census_pop_density

# filter california 
cali_pop_density = census_pop_density %>% 
  filter(str_detect(County, "^06"))

# write_csv(cali_pop_density, "./data/cali_pop_density.csv")
```

Calculating the percent urban and percent rural housing from each CA county from 2010 census data 
```{r Land Use}
##Search for land use/ urban rural vars by pulling codebook for census vars
#cdbk2010 = load_variables(2010, "sf1", cache = TRUE)

#View(cdbk2010)
#^^not running when knitting 

##Create a list of the relevant urban/ rural vars
urbanvars = c("H001001", "H002002", "H002005")

##Pull urban/ rural values, pivot to wide format, and rename census vars so they are meaningful
urban_housing_data = 
  get_decennial(
    geography = "county",
    variables = urbanvars,
    state = "CA"
    ) %>% 
  pivot_wider(
    names_from = "variable", 
    values_from = "value"
    ) %>% 
  dplyr::rename(
        tot_housing = H001001,
        urban_hous =  H002002, 
        rural_hous = H002005 
        ) 
  
##calculate % rural and % urban vars
urban_housing_data = mutate(urban_housing_data, 
         pct_urban = urban_hous / tot_housing,
         pct_rural = rural_hous / tot_housing, 
         pct_urban = round(pct_urban, 2), 
         pct_rural = round(pct_rural,2)
         )
  
##plot % urban
urban_housing_data %>%
  ggplot(aes(x = pct_urban, y = reorder(NAME, pct_urban))) + 
  geom_point()

##plot % rural
urban_housing_data %>%
  ggplot(aes(x = pct_rural, y = reorder(NAME, pct_rural))) + 
  geom_point()

##Perecent urban and % rural are perfect invesrses, can just use 1 in analysis. 
```


Viewing household income from acs from 2006-2010. 
```{r Household Income}
household_income_data = get_acs(geography = "county",
                           variables = "B19013_001",
                           state = "CA",
                           year = 2010
                           ) %>% 
                  select(-GEOID, -variable) %>% 
                  rename(hshld_income = estimate)

household_income_data %>%
  ggplot(aes(x = hshld_income, y = reorder(NAME, hshld_income))) + 
  geom_point()

```


Creating census dataset with all relevant variables 
```{r Joinind Census Data}
census_data = left_join(urban_housing_data, household_income_data, by = "NAME") %>% 
       rename(County = GEOID)

census_data = left_join(census_data, cali_pop_density, by = "County") %>% 
  select(County, NAME, everything())
census_data
##Created one dataset with all census vars. May want to confirm var names as a group and clean up Environment##
```

```{r correlation matrix of covariates and exposure}
### Calculate correlations


## join all dfs for correlation matrix
data_cormat <- census_data %>% 
  select(-County, -NAME, -county_name) %>% 
  mutate_all(as.numeric)

v.matrix <- round(cor(data_cormat, use = "pairwise.complete.obs", 
                    method = c("spearman")), 2)

v.matrix[upper.tri(v.matrix)] <- NA          

viz.cormat <- reshape2::melt(v.matrix, na.rm = TRUE) %>% 
  dplyr::rename(Correlation = value) 

 v.matrix
 
### Visualization

viz.cormat %>%
    ggplot(aes(Var1, Var2, fill = Correlation)) +
 geom_tile(color = "white") +
 scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
                      midpoint = 0.5,  space = "Lab", 
                      name = "Spearman\nCorrelation") +
  geom_text(aes(Var1, Var2, label = Correlation), color = "black", size = 5) +
#  theme_minimal(base_size = 14) + # minimal theme
  theme(
    axis.text.x = element_text(angle = 45, vjust = 1, size = 14, hjust = 1),
    axis.text.y = element_text(vjust = 1, size = 14, hjust = 1),
  #axis.title.x = element_text(size = 15),
  #axis.title.y = element_text(size = 15)
  axis.title.x = element_blank(),
  axis.title.y = element_blank(),
  panel.grid.major = element_blank(),
  panel.border = element_blank(),
  panel.background = element_blank(),
  axis.ticks = element_blank(),
  #legend.justification = c(1, 0),
  #legend.position = c(0.45, 0.8),
  legend.direction = "horizontal",
  legend.text = element_text(size = 14),
  legend.title = element_text(size = 14)) 
#  guides(fill = guide_colorbar(barwidth = 8, barheight = 1.5,
               # title.position = "top", title.hjust = 0.5))
```

NOAA DATA

Temperature data
```{r temperature}
# NOAA National Climate Data Center, "Climate at a Glance", county-level mapping
# month selected is the last month in the time scale
# summer average temperature, years 2011-2018, all counties (to check specific months)
# https://www.ncdc.noaa.gov/cag/county/mapping/4/pcp/201702/7/value

temp_2011 <- read_csv("./data/temp_2011.csv", col_names = TRUE) %>% 
  mutate(year = 2011)
temp_2012 <- read_csv("./data/temp_2012.csv", col_names = TRUE) %>% 
  mutate(year = 2012)
temp_2013 <- read_csv("./data/temp_2013.csv", col_names = TRUE) %>% 
  mutate(year = 2013)
temp_2014 <- read_csv("./data/temp_2014.csv", col_names = TRUE) %>% 
  mutate(year = 2014)
temp_2015 <- read_csv("./data/temp_2015.csv", col_names = TRUE) %>% 
  mutate(year = 2015)
temp_2016 <- read_csv("./data/temp_2016.csv", col_names = TRUE) %>% 
  mutate(year = 2016)
temp_2017 <- read_csv("./data/temp_2017.csv", col_names = TRUE) %>% 
  mutate(year = 2017)
temp_2018 <- read_csv("./data/temp_2018.csv", col_names = TRUE) %>% 
  mutate(year = 2018)


avg_summer_temp <- rbind(temp_2011, temp_2012, temp_2013, temp_2014, temp_2015,
                         temp_2016, temp_2017, temp_2018)

# write_csv(avg_summer_temp, "./data/avg_summer_temp.csv")

```

Annual Precipitation Data
```{r precipitation}
# annual precipitation, years 2011-2018, all counties 
# https://www.ncdc.noaa.gov/cag/county/mapping/4/pcp/201712/12/value

precip_2011 <- read_csv("./data/precip_2011.csv", skip = 3, col_names = TRUE) %>% 
  mutate(year = 2011)
precip_2012 <- read_csv("./data/precip_2012.csv", skip = 3, col_names = TRUE) %>% 
  mutate(year = 2012)
precip_2013 <- read_csv("./data/precip_2013.csv", skip = 3, col_names = TRUE) %>% 
  mutate(year = 2013)
precip_2014 <- read_csv("./data/precip_2014.csv", skip = 3, col_names = TRUE) %>% 
  mutate(year = 2014)
precip_2015 <- read_csv("./data/precip_2015.csv", skip = 3, col_names = TRUE) %>% 
  mutate(year = 2015)
precip_2016 <- read_csv("./data/precip_2016.csv", skip = 3, col_names = TRUE) %>% 
  mutate(year = 2016)
precip_2017 <- read_csv("./data/precip_2017.csv", skip = 3, col_names = TRUE) %>% 
  mutate(year = 2017)
precip_2018 <- read_csv("./data/precip_2018.csv", skip = 3, col_names = TRUE) %>% 
  mutate(year = 2018)


annual_precip <- rbind(precip_2011, precip_2012, precip_2013, precip_2014, precip_2015,
                         precip_2016, precip_2017, precip_2018)

#write_csv(annual_precip, "./data/annual_precip.csv")

```